### ISSUE TITLE
Superceded by fingerprint filter plugin

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-filter-anonymize#12]
Fingerprint plugin is the newer and more maintained plugin that serves the same purpose of replacing values with a consistent hash.   Having multiple plugins that perform the same task can be confusing to the end users.  Should we deprecate and remove this plugin from documentation moving forward - or direct users to the fingerprint filter plugin documentation on the anonymize page.

**Comment by acchen97** [comment]
@ppf2 thanks, I agree having multiple plugins for this is confusing. Let's deprecate anonymize immediately, and we can consider removing the plugin in 6.0.

@dedemorton do you mind helping us add a deprecation notice on the anonymize filter docs, which should also guide users towards fingerprint as the recommended alternative? Thanks in advance.

**Comment by dedemorton** [comment]
I've deprecated the plugin as of the 3.0.3 version of the plugin. The docs for that plugin won't show up in "current" for awhile, though, so I've tweaked the asciidoc files to include a note recommending the fingerprint filter plugin.
